### ISSUE TITLE
Figure out what the '#' transaction flag does and document accordingly

### ISSUE THREAD

**Issue by twilco** [twilco/beancount#10]
As mentioned in the title, we should figure out what the `#` transaction flag does and document our code accordingly.  Currently the flag is called `flag_hash`, rather than some of the other more useful flag names such as `flag_warning` or `flag_okay`.  [It is supported in the original grammar](https://bitbucket.org/blais/beancount/src/default/beancount/parser/grammar.y?fileviewer=file-view-default#grammar.y-274), but I'm not sure what it is.  Once we discover what this flag is, let's update that grammar rule name and document the flag.

**Comment by mbudde** [comment]
Looks like it's a flag used by the forecast plugin: https://bitbucket.org/blais/beancount/src/487cb9b0248427ac6882889b6b8bcc1665ce393e/beancount/plugins/forecast.py?at=default&fileviewer=file-view-default
