### ISSUE TITLE
Never panic when parsing

### ISSUE THREAD

**Issue by ThomasdenH** [twilco/beancount#28]
Currently, the parser uses `unwrap` and `expect`, but it would be more Rust-like and improve usability to use a special error type everywhere.

This type could give detailed diagnostics about what went wrong. Does Pest provide something like this already?

**Comment by twilco** [comment]
I agree with this proposal -- most Rust libraries probably shouldn't panic.  Pest provides very detailed errors (https://docs.rs/pest/2.1.3/pest/error/struct.Error.html), so I think we could map pertinent information from this to our own thin parser error type.

**Comment by mbudde** [comment]
Any suggestions for the concrete definition of the error type? I can come up with two types of errors we should probably distinguish:
- Parsing errors that is caused by bad input
- Parsing errors that is caused by the pest grammar being out of sync with the code converting the parse result into Beancount constructs.

**Comment by twilco** [comment]
I envision something like Servo's CSS parser errors — the error kind and the location.

https://github.com/servo/rust-cssparser/blob/cfd59cabd52fe9134315dbe1d43aa16261e0fd35/src/parser.rs#L41#L63

> Parsing errors that are caused by bad input

Agree.  It would be nice to be as specific as is possible for our `kind` variants.  It would be interesting to see what errors the [Beancount-proper implementation parser](https://github.com/beancount/beancount/tree/53e0c46bd8545a8ffb8a639e193ebfe0f2eb7ec7/beancount/parser) outputs.

**Comment by ThomasdenH** [comment]
[gammar.py](https://github.com/beancount/beancount/blob/53e0c46bd8545a8ffb8a639e193ebfe0f2eb7ec7/beancount/parser/grammar.py) has the errors, in the variants `ParserError`, `ParserSyntaxError` and `DeprecatedError`.
