### ISSUE TITLE
Support unicode in quoted strings (?)

### ISSUE THREAD

**Issue by twilco** [twilco/beancount#4]
Support for unicode characters in account names was added in #3.  However, [@mbudde mentioned we may also need to support unicode inside quoted strings](https://github.com/twilco/beancount/pull/3#issuecomment-463074090).  Let's confirm this is the case, and if so let's update our `quoted_str` / `quoted_char` rules to support unicode.

**Comment by mbudde** [comment]
Just checked and `quoted_str` already handles Unicode characters, since it uses `ANY`.

**Comment by twilco** [comment]
Ah yes, we can close this out then.
