### ISSUE TITLE
Underscore for commodity

### ISSUE THREAD

**Issue by ThomasdenH** [twilco/beancount#44]
Currently the parser doesn't accept an underscore for commodity names, while beancount does.

**Comment by mbudde** [comment]
Can you give an example?

**Comment by ThomasdenH** [comment]
Yes, something like 
```beancount
1867-01-01 commodity COM_NAME
```

**Comment by mbudde** [comment]
That should work already: https://github.com/twilco/beancount/blob/1ba0a3ee79c15f8b3f79b327398a7be8bcf88689/beancount-parser/src/beancount.pest#L41-L43

**Comment by ThomasdenH** [comment]
Oh, wait. Maybe something else went wrong. I'll open this issue again if I find it. Thanks!
